<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace local_coursedynamicrules\local\service;

use grade_grade;
use grade_item;

/**
 * Carries the result of a reinforcement activity back onto the activity the student failed.
 *
 * Moodle has no native "this activity replaces that one": its recovery mechanisms all live INSIDE
 * a single activity (a quiz's grading method across attempts, an assignment's reopened attempts).
 * A reinforcement generated by a rule is a different activity, so the link between the two has to
 * be recorded when it is created and acted upon when it is graded.
 *
 * The source grade is frozen at creation time. Reading it live would be wrong: once the first
 * combination has written onto the source, a later re-grade of the reinforcement would compare
 * against the already-overwritten value and the student's original mark would be lost for good.
 *
 * @package    local_coursedynamicrules
 * @copyright  2026 Industria Elearning <info@industriaelearning.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class grade_combination_service {
    /** @var string Table linking a generated activity to its rule, student and source activity. */
    public const TABLE = 'local_coursedynamicrules_aigrade';

    /**
     * Whether this action has already generated an activity for this student.
     *
     * The scheduled tasks re-evaluate their rules forever: no_complete_activity_task runs every
     * minute and its only gate is a fixed date, so once that date passes it is true on every run;
     * course_inactivity_task runs every six hours and only checks the course dates. Without this
     * question, a rule combining one of them with this action generates a fresh activity - and a
     * fresh paid AI call - on every single pass.
     *
     * @param int $actionid
     * @param int $userid
     * @return bool
     */
    public static function already_generated(int $actionid, int $userid): bool {
        global $DB;

        return $DB->record_exists(self::TABLE, ['actionid' => $actionid, 'userid' => $userid]);
    }

    /**
     * Record that an activity was generated for a student.
     *
     * Written for every mode, not only the ones that feed a source activity, because the row is
     * what {@see self::already_generated()} reads to stop the same activity being generated again
     * on the next scheduled pass.
     *
     * @param int $courseid
     * @param int $ruleid
     * @param int $actionid
     * @param int $userid Student the activity was generated for.
     * @param int $cmid Course module of the generated activity.
     * @param int $sourcecmid Course module whose grade is combined or replaced, 0 when none.
     * @param string $mode grade_isolation_service::MODE_*.
     * @param string $rule The formula or policy chosen, empty when the mode takes none.
     * @return int Row id.
     */
    public static function record_generation(
        int $courseid,
        int $ruleid,
        int $actionid,
        int $userid,
        int $cmid,
        int $sourcecmid,
        string $mode,
        string $rule
    ): int {
        global $DB;

        if (!in_array($mode, grade_isolation_service::modes_needing_source(), true)) {
            // Nothing to carry anywhere: the row exists purely as the "already generated" marker.
            $sourcecmid = 0;
        }

        return (int) $DB->insert_record(self::TABLE, (object) [
            'courseid' => $courseid,
            'ruleid' => $ruleid,
            'actionid' => $actionid,
            'userid' => $userid,
            'cmid' => $cmid,
            'sourcecmid' => $sourcecmid,
            'grademode' => $mode,
            'graderule' => $rule,
            'sourcegrade' => self::current_grade($sourcecmid, $userid),
            'timecreated' => time(),
        ]);
    }

    /**
     * The student's final grade on an activity right now, or null when they have none.
     *
     * @param int $cmid
     * @param int $userid
     * @return float|null
     */
    public static function current_grade(int $cmid, int $userid): ?float {
        $item = self::primary_item($cmid);
        if (!$item) {
            return null;
        }
        $grade = grade_grade::fetch(['itemid' => $item->id, 'userid' => $userid]);

        return ($grade && $grade->finalgrade !== null) ? (float) $grade->finalgrade : null;
    }

    /**
     * The first gradable item of a course module, which is the one a combination acts on.
     *
     * @param int $cmid
     * @return grade_item|null
     */
    public static function primary_item(int $cmid): ?grade_item {
        $cm = get_coursemodule_from_id(null, $cmid, 0, false, IGNORE_MISSING);
        if (!$cm) {
            return null;
        }
        $items = grade_isolation_service::gradable_items((int) $cm->course, $cm->modname, (int) $cm->instance);
        if (empty($items)) {
            return null;
        }
        // Deterministic: the lowest itemnumber is the module's main grade.
        usort($items, fn(grade_item $a, grade_item $b) => $a->itemnumber <=> $b->itemnumber);

        return reset($items);
    }

    /**
     * Work out the grade a source activity should end up with.
     *
     * Pure arithmetic on values already expressed in the SOURCE activity's scale, so it can be
     * tested without a gradebook. Returns null when nothing should be written.
     *
     * @param string $mode grade_isolation_service::MODE_*.
     * @param string $rule grade_isolation_service::RULE_*.
     * @param float|null $sourcegrade The frozen original grade, null when the student had none.
     * @param float $newgrade Reinforcement grade, already scaled to the source's maximum.
     * @param float|null $gradepass The source activity's pass grade, if it has one.
     * @return float|null
     */
    public static function compute(
        string $mode,
        string $rule,
        ?float $sourcegrade,
        float $newgrade,
        ?float $gradepass
    ): ?float {
        $original = $sourcegrade ?? 0.0;

        if ($mode === grade_isolation_service::MODE_COMBINE) {
            if ($rule === grade_isolation_service::RULE_MEAN) {
                return ($original + $newgrade) / 2;
            }

            return max($original, $newgrade);
        }

        if ($mode !== grade_isolation_service::MODE_REPLACE) {
            return null;
        }

        if ($rule === grade_isolation_service::RULE_ALWAYS) {
            return $newgrade;
        }

        if ($rule === grade_isolation_service::RULE_CAP) {
            // A capped recovery may not exceed the pass mark, and may never leave the student
            // worse off than the attempt they are recovering from.
            $capped = ($gradepass !== null && $gradepass > 0) ? min($newgrade, $gradepass) : $newgrade;

            return max($original, $capped);
        }

        // RULE_IMPROVE.
        return max($original, $newgrade);
    }

    /**
     * React to a reinforcement activity being graded: carry the result onto the source activity.
     *
     * @param int $cmid Course module that was graded.
     * @param int $userid Student who was graded.
     * @return bool Whether a source grade was written.
     */
    public static function handle_graded(int $cmid, int $userid): bool {
        global $DB;

        $link = $DB->get_record(self::TABLE, ['cmid' => $cmid, 'userid' => $userid]);
        if (!$link) {
            // Not a generated activity this plugin is tracking. This is also what stops the write
            // below from looping: the source activity is never itself a tracked cmid.
            return false;
        }

        if ((int) $link->sourcecmid === 0) {
            // A marker row for a mode that carries nothing. Nothing to write.
            return false;
        }

        $sourceitem = self::primary_item((int) $link->sourcecmid);
        $newitem = self::primary_item($cmid);
        if (!$sourceitem || !$newitem) {
            return false;
        }

        $newgrade = self::current_grade($cmid, $userid);
        if ($newgrade === null) {
            // Graded event without a grade: nothing to carry over yet.
            return false;
        }

        // The two activities rarely share a maximum, so the reinforcement is expressed as a
        // proportion of its own scale and then read against the source's.
        $newmax = (float) $newitem->grademax;
        $sourcemax = (float) $sourceitem->grademax;
        $scaled = $newmax > 0 ? ($newgrade / $newmax) * $sourcemax : 0.0;

        $gradepass = ((float) $sourceitem->gradepass) > 0 ? (float) $sourceitem->gradepass : null;
        $result = self::compute(
            $link->grademode,
            $link->graderule,
            $link->sourcegrade === null ? null : (float) $link->sourcegrade,
            $scaled,
            $gradepass
        );

        if ($result === null) {
            return false;
        }

        $sourceitem->update_final_grade(
            $userid,
            $sourceitem->bounded_grade($result),
            'local_coursedynamicrules'
        );

        return true;
    }

    /**
     * The activity a rule is watching, which is the one a reinforcement recovers.
     *
     * Taken from the rule's own "Grade in activity" condition rather than asked for again: the
     * teacher already named it there, and a second selector could disagree with the condition that
     * triggers the rule.
     *
     * @param int $ruleid
     * @return int|null Course module id, or null when the rule watches no graded activity.
     */
    public static function resolve_source_cmid(int $ruleid): ?int {
        global $DB;

        $rows = $DB->get_records('local_coursedynamicrules_condition', [
            'ruleid' => $ruleid,
            'conditiontype' => 'grade_in_activity',
        ], 'id ASC');

        foreach ($rows as $row) {
            $params = json_decode($row->params ?? '');
            $cmid = isset($params->cmid) ? (int) $params->cmid : 0;
            if ($cmid > 0) {
                return $cmid;
            }
        }

        return null;
    }

    /**
     * The display name of an activity, for putting in front of the teacher.
     *
     * @param int $cmid
     * @return string Empty when the module is gone.
     */
    public static function activity_name(int $cmid): string {
        $cm = get_coursemodule_from_id(null, $cmid, 0, false, IGNORE_MISSING);

        return $cm ? format_string($cm->name) : '';
    }

    /**
     * Forget every link belonging to an action, so deleting a rule leaves no dangling rows.
     *
     * @param int $actionid
     */
    public static function forget_action(int $actionid): void {
        global $DB;
        $DB->delete_records(self::TABLE, ['actionid' => $actionid]);
    }
}
